import Head from 'next/head'
import Image from 'next/image'

import type { NextPage } from 'next'
import { GetStaticProps } from 'next'

import { getAllFilesFrontMatter } from '../lib/mdx'
import Link from '../components/Link'
import { useState } from 'react'


type Props = {
    posts: {
        title: string;
        slug: string;
        image: string;
    }[];
};

const Home: NextPage<Props> = ({ posts }) => {

    const [search, setSearch] = useState('')

        const postsResult = posts.filter(post => (
            post.title.toLocaleLowerCase().includes(search.toLowerCase())
        ))
    

    return (
        <div className="flex flex-col h-screen">
            <Head>
                <title>Blog MDX</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className='p-3 border-b'>
                <div className='container px-5 mx-auto flex justify-between items-center'>
                    <p className='text-slate-900 font-black text-lg'>MDX Blog</p>
                    <div className="relative">
                        <input
                            aria-label="Search articles"
                            type="text"
                            onChange={(e) => setSearch(e.target.value)}
                            placeholder="Search articles"
                            className="px-4 py-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500 block w-full rounded-md bg-white text-gray-900"
                        />
                        <svg
                            className="absolute right-3 top-3 h-5 w-5 text-gray-400 dark:text-gray-300"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                        >
                            <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth={2}
                                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                            />
                        </svg>
                    </div>
                </div>
            </header>

            <main className='container px-5 mx-auto mt-10 space-y-4 max-w-xl flex-1' >

                {
                    postsResult.map(post => (
                        <Link key={post.slug} href={`/blog/${post.slug}`}
                            className="block rounded border border-gray-200 p-4 hover:bg-gray-100 cursor-pointer">
                            <h3 className='cursor-pointer'>{post.title}</h3>

                        </Link>
                    ))
                }

            </main>



            <footer className='p-5 mt-16'>
                <div className='container px-5 mx-auto'>
                    <a
                        href="https://github.com/tonatiujsanchez"
                        target="_blank"
                        rel="noopener noreferrer"
                        className='flex items-center justify-center'
                    >

                        <span>
                            <Image src="/vercel.svg" alt="Vercel Logo" width={16} height={16} />
                            {' '}Tonatiuj Sánchez
                        </span>
                    </a>
                </div>
            </footer>
        </div>
    )
}




export const getStaticProps: GetStaticProps = async (ctx) => {
    const posts = await getAllFilesFrontMatter("posts")

    return {
        props: {
            posts
        }
    }
}

export default Home
